# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - udunits-bin # for RNetCDF
      - libudunits2-dev # for RNetCDF
      - libcairo2-dev # for RNetCDF
      - libxt-dev # for RNetCDF